exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start waybar@hyprland
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- dunst
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store

exec-once = [workspace 1 silent] uwsm app -- $terminal
exec-once = [workspace 2 silent] uwsm app -- $browser
exec-once = [workspace 3 silent] uwsm app -- $mail
