$terminal = kitty
# $browser = brave --enable-features=UseOzonePlatform --ozone-platform=wayland
# $browser_private = brave --incognito --enable-features=UseOzonePlatform --ozone-platform=wayland
# $browser = brave --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
# $browser_private = brave --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --incognito
$browser = brave --hide-crash-restore-bubble
$browser_private = brave --hide-crash-restore-bubble --incognito
# $browser = librewolf
# $browser_private = librewolf --private-window
$mail = thunderbird
$menu = wofi --show run
