exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = uwsm app -- /usr/libexec/hyprpolkitagent
exec-once = uwsm app -- ~/.config/waybar/scripts/start-waybar.sh
# exec-once = ibus-daemon -rxRd
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- dunst

exec-once = [workspace 1 silent] uwsm app -- $terminal
exec-once = [workspace 2 silent] uwsm app -- $browser
exec-once = [workspace 3 silent] uwsm app -- $mail
