# See https://wiki.hyprland.org/Configuring/Monitors/
# columns: [name, resolution, position, scale]
# monitor=,preferred,auto,auto
# monitor = , highres, auto, 1.2
monitor = , 3840x2160@60, auto, 1.2

# https://wiki.hyprland.org/Configuring/XWayland/#hidpi-xwayland
xwayland {
  force_zero_scaling = true
}
